### ISSUE TITLE
Duplicate authorization

### ISSUE THREAD

**Issue by ikatyang** [dependencies-io/support#2]
Thanks for the great tool 👍 , but it seems there are some problem for the authorization.

If I click the login button on the homepage:

![image](https://user-images.githubusercontent.com/8341033/28490028-70d4d0e8-6f03-11e7-9862-448e0ad845af.png)
![image](https://user-images.githubusercontent.com/8341033/28490107-20110874-6f04-11e7-8424-82bcc6660ed0.png)

It always asks me to authorize again even I have already authorized.

![image](https://user-images.githubusercontent.com/8341033/28490033-828c52ca-6f03-11e7-8325-d151bdbceb2d.png)

**Comment by davegaeddert** [comment]
Thanks @ikatyang! I'll take a look and see if that authorization screen can be avoided after the first time, but from what I've seen thus far, that's just how it works. The OAuth part of a "GitHub App" seems to behave differently than how the old OAuth integrations do. I'll poke around their forum and see if I find anything.

**Comment by davegaeddert** [comment]
Thanks for closing, didn't even realize that GitHub made a change to this!
