### ISSUE TITLE
Dependency downgraded after new minor release in previous major version

### ISSUE THREAD

**Issue by Vinnl** [dependencies-io/support#20]
I received a pull request with [this commit](https://gitlab.com/Flockademic/Flockademic/commit/05b623b76885a5f3236f2361e30f28b430e41168) from Dependencies.io. As you can see, although the title is "Update mime from 1.4.1 to 1.6.0", it actually downgrades it from 2.0.3 to 1.6.0. I don't suppose that's meant to happen?

**Comment by davegaeddert** [comment]
Hey @Vinnl, thanks for opening the issue. We did have a bug for a couple days in the js-npm collector, which got fixed yesterday (after you experienced it). More about it here: https://github.com/dependencies-io/collector-js-npm/issues/23

I'm going to close this for now but be sure to let us know if you have any other issues. Thanks!

**Comment by Vinnl** [comment]
Ah, thanks for the heads-up - I'll open a new bug if I experience this again then.
