### ISSUE TITLE
Builds scheduled for 24 UTC don't run

### ISSUE THREAD

**Issue by Harmon758** [dependencies-io/support#24]

**Comment by davegaeddert** [comment]
Sure enough. Thanks. It's required to between 0-23 now.

**Comment by Harmon758** [comment]
Getting `Error saving settings: null value in column "build_hour" violates not-null constraint` when trying to set it to 0 now.

**Comment by davegaeddert** [comment]
Found a bug in the API. Give it one more try?!

**Comment by Harmon758** [comment]
Both aspects of the issue seem to be fixed now. Thanks!
