### ISSUE TITLE
Removing a project

### ISSUE THREAD

**Issue by szepeviktor** [dependencies-io/support#29]
Please provide a clear way to remove a project.
Thanks.

**Comment by davegaeddert** [comment]
GitHub projects should be removed by uninstalling the GitHub app (https://github.com/apps/dependencies). It needs to be done from the GitHub side, but yes we should make this more clear. Thanks.

**Comment by szepeviktor** [comment]
All I could do is revoke the GitLAB token.

**Comment by davegaeddert** [comment]
I see, sorry I assumed you were using GitHub. You're correct, we don't have a way to remove a GitLab project yet. Let me know if you want me to remove one for you.

**Comment by szepeviktor** [comment]
Please look into #27 and remove my one project.

**Comment by davegaeddert** [comment]
Done. It's on our list to get a delete button added.

**Comment by YesThatAllen** [comment]
> [removing a project] needs to be done from the GitHub side, but yes we should make this more clear. Thanks.
>It's on our list to get a delete button added.

I came here for this, thanks.

**Comment by davegaeddert** [comment]
The project settings tab now has a button to remove GitLab repos or a message to uninstall the GitHub App if it is a GitHub repo.

**Comment by szepeviktor** [comment]
Thanks.
