### ISSUE TITLE
Not Detecting Correct Version for Drupal 8.5.3

### ISSUE THREAD

**Issue by kclarkson** [dependencies-io/support#30]
I am trying to use dependecies.io to manage drupal composer installation. The current version is listed at 8.5.3 but the dependencies.io is only updating the lock file to 8.5.1. 

Is there something that I need to adjust in my repo in order to get it to update correctly? 

https://app.dependencies.io/projects/github/ksu-aaf/app-portal

**Comment by alexdesignworks** [comment]
@davegaeddert Why would anyone want to use `--ignore-platform-reqs` if it will make installation of incorrect versions possible? `--ignore-platform-reqs` should be discouraged by DIO because it will produce inconsistent results!

**Comment by davegaeddert** [comment]
I'm going to close this in favor of https://github.com/dependencies-io/php/issues/24 on the php repo itself. Thanks for the feedback.
