### ISSUE TITLE
Jest - Don't link to every PR in the release

### ISSUE THREAD

**Issue by rickhanlonii** [dependencies-io/support#31]
Hey all 👋

We're currently getting a lot of spam on old Jest PRs from the Dependencies bot including our CHANGELOG it's PRs to update to Jest 23. See [this PR](https://github.com/facebook/jest/pull/5601) for an example.

Is it possible to have the bot post these comments inside of a code block or to include a link to the CHANGELOG instead? That should prevent Github from linking every PR you open to every PR in our release.

Thanks!

**Comment by davegaeddert** [comment]
Thanks @rickhanlonii, I totally understand that the reference links are annoying! Looks like there are some from us and from other similar services too. We'll see if there's anything we can do -- I know there has been conversation with GitHub at some point about allowing links to PRs without creating those references on the original PR, but AFAIK nothing has happened there. We can maybe look into rewriting those links to go through some kind of redirect server or something...

**Comment by rickhanlonii** [comment]
Ah, I understand. It would be really helpful to take the short term strategy of linking to our changelog instead of embedding a copy of the notes in the PR (I've reached out to other bots as well)

**Comment by rickhanlonii** [comment]
Note that neither Greenkeeper or Dependabot are spamming links anymore, I believe this is the only bot remaining. Here's an example from the [most recent release](https://github.com/facebook/jest/pull/6130) (the example in the OP is an old release).

**Comment by rickhanlonii** [comment]
Any update here?

**Comment by davegaeddert** [comment]
Hey @rickhanlonii, it's on the list for this week. I'll let you know what we decide to do.

**Comment by davegaeddert** [comment]
We're going to try modifying the links to issues and PRs to go through a redirect server (e.g. https://www.dependencies.io/github-redirect/facebook/jest/pull/6130) to avoid the back references for now. We'll roll it out to all the components over the next day or so. @rickhanlonii let me know if you have any more questions/feedback about this in the future. Thanks!

**Comment by rickhanlonii** [comment]
Awesome, thanks a ton!
