### ISSUE TITLE
Get changelog from github releases

### ISSUE THREAD

**Issue by moimael** [dependencies-io/support#32]
Hi,

A lot of npm dependencies have their changelogs in the Github release page. Would it be possible to scrap it automatically if it's there ?

Thanks !

**Comment by davegaeddert** [comment]
Hi @moimael -- it's a little finicky but it actually should be pulling from GitHub releases if they exist and it can find the right repo. Can you point me to a couple specific npm packages that didn't have changelogs but could have? Thanks!

**Comment by moimael** [comment]
Hi, hum I haven't seen this work for any of our dependencies and most of them have github releases with changelogs.

For example react, react-dropzone, react-datepicker, react-motion, ...

I have a list of probably 20+ deps in the same situation.

**Comment by davegaeddert** [comment]
I will check some of those specifically. It looks for changelogs in a number of places and it's possible it's getting hung up somewhere with the GitHub API.

**Comment by davegaeddert** [comment]
@moimael any chance you could point me towards a specific version of react, for example, that didn't have a changelog? In spot checking the versions in the database, I'm seeing the changelog content. Any specific info (or links to public PRs) you could provide would be helpful in tracking down what the issue might be.

**Comment by moimael** [comment]
Some examples: 

![screenshot from 2018-07-19 10-26-53](https://user-images.githubusercontent.com/1479859/42930892-8d894e5a-8b3e-11e8-88dd-f08aba70d2e8.png)
![screenshot from 2018-07-19 10-27-03](https://user-images.githubusercontent.com/1479859/42930898-8fe04262-8b3e-11e8-8e0e-6cb36f6595f3.png)
![screenshot from 2018-07-19 10-27-13](https://user-images.githubusercontent.com/1479859/42930902-93d44daa-8b3e-11e8-9209-dd58bed1a918.png)

**Comment by davegaeddert** [comment]
Thanks for getting back to me on this. Seems odd -- I know that the data is there (at least right now it is but maybe a month ago it wasn't). We'll have to dig deeper and see where there might be a hiccup.

![image](https://user-images.githubusercontent.com/649496/42963727-b1c07048-8b5a-11e8-8388-86c4d9a5bff7.png)

We'll keep an eye on some PR content going out and see if we can spot one of these issues closer to when it happens.

Sorry for the trouble!

**Comment by noseglid** [comment]
We haven't seen any changelogs so far in any of our PRs. Would love to see this get some love so I don't have to find each repo manually all the time.

**Comment by davegaeddert** [comment]
Thanks for pushing on this. We did finally find what looks like the problem and pushed a few changes. We'll keep an eye on it.

**Comment by moimael** [comment]
It's still not working for us, just got ~25 update PR for one of our project (we have a monthly task) and none of them has a changelog.

**Comment by davegaeddert** [comment]
Alright, we're going to have to look into specifics again. @noseglid and @moimael are you both using GitHub repos or GitLab? And can you give me the names of few packages (and their languages/registries) that recently didn't have changelogs?

Thanks again.

**Comment by moimael** [comment]
Yes we are using private Github repositories.

I'm pretty confident it's not a package issue here since it's consistently not working for any package. Even when we add new dependencies. And even well known and masively used packages.

So for yarn/npm packages, that we had PR made by dependencies.io recently and didn't had any changelog:

- optimize-css-assets-webpack-plugin
- lint-staged
- jest
- eslint-config-airbnb
- sinon
- deep-diff
- jest-styled-components
- react-dropzone
- autoprefixer
- assets-webpack-plugin
- babel-eslint
- yup
- @types/recompose
- @types/node
- eslint-plugin-react
- eslint-plugin-import
- eslint
- babel-loader
- eslint-config-prettier
- react-datepicker
- @types/ramda
- @types/react-redux
- aphrodite

And so much more, but I don't have the courage to write all of them down. Bottom line, none of our dependencies update PR on 5 different pretty big projects is showing any changelog. I'm highly confident no matter what's the dependency, it's just not working at all.

**Comment by noseglid** [comment]
Yes, also github. Here's our weekly update (which we go this monday);
```
yarn.lock
32 transitive dependencies were updated, 10 were added, and 0 removed. View the git diff for more details about exactly what changed.

The following 8 direct dependencies were updated:

@types/node was updated from 10.9.2 to 10.9.4
We didn't find any content for 10.9.4. Feel free to open an issue at dependencies-io/support to suggest any improvements.

@types/react was updated from 16.4.12 to 16.4.13
We didn't find any content for 16.4.13. Feel free to open an issue at dependencies-io/support to suggest any improvements.

@types/react-beautiful-dnd was updated from 7.1.1 to 7.1.2
We didn't find any content for 7.1.2. Feel free to open an issue at dependencies-io/support to suggest any improvements.

optimize-css-assets-webpack-plugin was updated from 5.0.0 to 5.0.1
We didn't find any content for 5.0.1. Feel free to open an issue at dependencies-io/support to suggest any improvements.

react-beautiful-dnd was updated from 9.0.1 to 9.0.2
We didn't find any content for 9.0.2. Feel free to open an issue at dependencies-io/support to suggest any improvements.

react-md was updated from 1.5.0 to 1.5.1
We didn't find any content for 1.5.1. Feel free to open an issue at dependencies-io/support to suggest any improvements.

typescript was updated from 3.0.1 to 3.0.3
We didn't find any content for 3.0.3. Feel free to open an issue at dependencies-io/support to suggest any improvements.

webpack-dev-server was updated from 3.1.6 to 3.1.7
We didn't find any content for 3.1.7. Feel free to open an issue at dependencies-io/support to suggest any improvements.
```

All of them don't have changelogs, but e.g. `webpack-dev-server` had both the [releases tab of github](https://github.com/webpack/webpack-dev-server/releases/tag/v3.1.7) and its [`CHANGELOG.md`](https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md#317-2018-08-29) properly filled out

**Comment by davegaeddert** [comment]
Thanks for the detail. I agree there is some larger problem here and it is not package-specific, but we also have plenty of examples where changelogs for other packages are coming through correctly, so I just want to make sure we're looking at some of the same ones that you are. I think that it may be some kind of GitHub API token issue but that's why I want to look at specific packages again (and it looks like all of these examples are from npm). 

Sorry -- I know this is dragging out longer than any of us want it to! I appreciate your patience though.

**Comment by davegaeddert** [comment]
Alright, I'm fairly confident we found the main problem this time. Some request headers were automatically being converted to lower-case in a specific environment but not in others. As @noseglid mentioned, not all of the packages above have discoverable changelogs but there should at least be a handful that do.

The change should be immediate -- so let me know if you're still not seeing changelogs.

**Comment by noseglid** [comment]
We're getting changelogs 🙌 !

**Comment by davegaeddert** [comment]
Finally! Glad to hear it. I will close this for now. If anybody has more questions in the future -- please don't hesitate. Thanks again.
