### ISSUE TITLE
PRs and issues are getting polluted with long list of references.

### ISSUE THREAD

**Issue by IvanGoncharov** [dependencies-io/support#33]
![image](https://user-images.githubusercontent.com/8336157/41803497-1a392620-7692-11e8-9a7f-600ca6585788.png)

It's the same exact problem for every dependency update tool 🤦‍♂️
For details see here: https://github.com/dependabot/dependabot-core/issues/431
Here is a fix implemented by all other tools: https://github.com/dependabot/dependabot-core/issues/431#issuecomment-385026144
Please implement the same fix for your tool 🙏

**Comment by davegaeddert** [comment]
@IvanGoncharov can you point me towards a current example? I believe this was fixed a couple of weeks ago: https://github.com/dependencies-io/support/issues/31

I'll close it for now, but if there's still a problem, let me know!

**Comment by edmorley** [comment]
Hi!

This PR got a number of references 4 hours ago:
https://github.com/facebook/react/pull/13598

**Comment by davegaeddert** [comment]
Sure enough. We'll try and figure out why!

**Comment by edmorley** [comment]
Many thanks! Could this issue be reopened in the meantime? :-)

**Comment by davegaeddert** [comment]
Yep, sorry I haven't had time to dig into this yet. At first glance, I didn't see any issues...

Here's a chunk of the changelog that came through
```
## 16.5.1 (September 13, 2018)

### React

* Improve the warning when `React.forwardRef` receives an unexpected number of arguments. ([andresroberto](https://github.com/andresroberto) in [#13636](https://github.com/facebook/react/issues/13636))

### React DOM

* Fix a regression in unstable exports used by React Native Web. ([aweary](https://github.com/aweary) in [#13598](https://github.com/facebook/react/issues/13598))
* Fix a crash when component defines a method called `isReactComponent`. ([gaearon](https://github.com/gaearon) in [#13608](https://github.com/facebook/react/issues/13608))
* Fix a crash in development mode in IE9 when printing a warning. ([link-alex](https://github.com/link-alex) in [#13620](https://github.com/facebook/react/issues/13620))
* Provide a better error message when running `react-dom/profiling` with `schedule/tracking`. ([bvaughn](https://github.com/bvaughn) in [#13605](https://github.com/facebook/react/issues/13605))
* If a `ForwardRef` component defines a `displayName`, use it in warnings. ([probablyup](https://github.com/probablyup) in [#13615](https://github.com/facebook/react/issues/13615))

### Schedule (Experimental)

* Add a separate profiling entry point at `schedule/tracking-profiling`. ([bvaughn](https://github.com/bvaughn) in [#13605](https://github.com/facebook/react/issues/13605))
```

And here's the code that should have replaced the links:
https://github.com/dependencies-io/deps/blob/f2cb8aef7cac3f5d18e656b75fcef451a67321b8/internal/pullrequest/github/utils.go#L5-L12

**Comment by davegaeddert** [comment]
Took me a while to realize the obvious -- these references are coming from some of the few users left on our original update system, which is no longer supported. We're in the process of making plans to shut down that version entirely.

**Comment by edmorley** [comment]
Hi! I don't suppose we're any closer to getting people to migrate from the old system, or else modifying the old system to put the entire changelog in a markdown code block (backticks)? :-)

**Comment by davegaeddert** [comment]
Hi @edmorley, thanks for following up! No news yet unfortunately. We have some internal plans to move away from v1 by the end of the year, but are still working through some other projects. If you can point me towards the most recent examples you're seeing, I can try to get an idea of the volume and consider reaching out to those customers or putting a temporary fix in place.

**Comment by edmorley** [comment]
Ok, thank you for the update. 

Example PR:
https://github.com/facebook/react/pull/14083

**Comment by davegaeddert** [comment]
We'll be pushing out a fix for this today... better late than never? Sorry it took so long!
