### ISSUE TITLE
Deprecation of GitHub issue creation

### ISSUE THREAD

**Issue by Harmon758** [dependencies-io/support#34]
Since https://github.com/dependencies-io/actor-repo-issue has been deprecated as part of v1, are there any plans for an equivalent functionality in v2?

**Comment by davegaeddert** [comment]
Hi @Harmon758. We left a place for it in v2, but didn't actually build it in. At this point, the vast majority of users are happy with getting PRs over issues, so we aren't planning to add it anytime soon. Hope that helps.
