### ISSUE TITLE
Internal error starting collectors

### ISSUE THREAD

**Issue by Harmon758** [dependencies-io/support#35]
Getting this error on both manual and scheduled v1 builds:
![image](https://user-images.githubusercontent.com/9403740/42253433-776c781a-7f07-11e8-8a23-eab668489c31.png)
It seems to be happening randomly.
The first occurrence was 4 days ago on a scheduled build. Starting a build manually failed with the same error the first time, but succeeded the second time.
It happened again today, and this time it took seven manual builds for one to succeed.

**Comment by davegaeddert** [comment]
Hey @Harmon758, we've noticed some issues lately with the autoscaling on v1. We've provisioned a new set of nodes and cleaned up some things on the back end. Let me know if you continue to have issues with v1.

**Comment by Harmon758** [comment]
@davegaeddert, getting this error again.
