### ISSUE TITLE
Don't `@` mention users via changelogs

### ISSUE THREAD

**Issue by asottile** [dependencies-io/support#39]
It would be really really awesome if mentions in changelogs didn't trigger.  As it is right now, whenever I contribute to a ~popular project (for example [tox](https://github.com/tox-dev/tox)) my email becomes a torrential downpour of mentions as the world upgrades to the latest version.

Here's an example PR: https://github.com/dropseed/sweep/pull/55

Linking to the users which contributed _is_ useful however -- maybe manually expand mentions using something like this?:

```markdown
[**@(zero width whitespace character)username**](https://github.com/username)
```

**Comment by davegaeddert** [comment]
Sorry about that @asottile! We do try to prevent the mentions, but it looks like maybe those had a `\` in front of them which we didn't account for. I'll see if we can get it updated.

**Comment by davegaeddert** [comment]
Pushing out a fix now. Some of the changelogs may be cached for a few days, but if you get emails after that, be sure to let us know.
