### ISSUE TITLE
Support dot file style filename for configuration file

### ISSUE THREAD

**Issue by Harmon758** [dependencies-io/support#40]
i.e. `.dependencies.yml`
Currently, using the above filename causes the "Start a build manually" button on v1 to seemingly do nothing, with no error message.

**Comment by davegaeddert** [comment]
Just curious, is there a particular reason you want to use the dot style? To make it a hidden file?

**Comment by Harmon758** [comment]
That would be one use case, yes.
Personally, I have a project with other YAML files, for configuration of other services and the like, which all use dot style filenames. This seems to be standard, and `dependencies.yml` just seems out of place grouped among other non-YAML files that don't use dot style filenames in the folder/repository, so it's more of a visual preference for me.

**Comment by davegaeddert** [comment]
Going to close this for now in favor of the other issue. I agree though -- there should be some kind of support for using a hidden file (whether we make it an option or try to detect it automatically will be the only question).
