### ISSUE TITLE
Locking a version to v1 doesn't appear to work when there's a v10

### ISSUE THREAD

**Issue by Vinnl** [dependencies-io/support#42]
I might be misdiagnosing this, but... In [my `dependencies.yml`](https://gitlab.com/Flockademic/Flockademic/blob/dev/dependencies.yml) I think I've correctly specified to lock `ts-jest` to its current minor version (23.1.4) for most of my projects. The project released a new version (23.10.4 - note that it skipped 23.2 to 23.9) that I would prefer not to use yet, which is why I locked it with `L.L.Y`.

Nevertheless, I still received [three](https://gitlab.com/Flockademic/Flockademic/merge_requests/1063) [pull](https://gitlab.com/Flockademic/Flockademic/merge_requests/1058) [requests](https://gitlab.com/Flockademic/Flockademic/merge_requests/1061) updating `ts-jest` to the `.10` version.

I might be doing it wrong, otherwise perhaps dependencies.io has some trouble discerning between `.1` and `.10`, or perhaps with skipped versions.

**Comment by davegaeddert** [comment]
Hey @Vinnl, I think that you may be mixing up the "manifest" updates vs "lockfile" updates (understandably, I might add!). The `filters` (under `manifest_updates`) are intended to give you more control over version _outside_ of the package range you're currently using. In your case, it looks like your range is `^23.0.0` and so `23.10` is actually still in range of what you're asking yarn to install, so the PRs you're getting ("lockfile" updates) are just the result of yarn doing what you're asking for.

Does that make any sense? Simply put, I think you'll just want to change your package.json ranges to `<23.10` or something.

Let me know if that doesn't make sense!

**Comment by Vinnl** [comment]
That does make sense, thanks for the explanation!
