### ISSUE TITLE
Error updating version of software

### ISSUE THREAD

**Issue by ibaum** [dependencies-io/support#43]
An update is being found, but clicking on the "Update to vFOO" button results in a job failed error. 

The failed job is https://app.dependencies.io/j/1c206614-7f94-4121-8b80-393a5cee4107

The error log is 

```
HEAD is now at 462289b Update git_repos.yml

Switched to a new branch 'dependencies_io/deps/update-1c206614'

Traceback (most recent call last):
  File "/usr/src/app/entrypoint.py", line 12, in <module>
    act()
  File "/usr/src/app/act.py", line 38, in act
    find_str = pattern.format(
AttributeError: 'CommentedMap' object has no attribute 'format'
```

Root project is https://gitlab.com/ibaum/omnibus-gitlab

**Comment by davegaeddert** [comment]
Hey @ibaum, I think you need quotes in your YAML so that it is parsed correctly (starting with `{` makes it think it is a dict instead of string).

`GITALY_SERVER_VERSION: {version}` should be `GITALY_SERVER_VERSION: "{version}"`
