### ISSUE TITLE
Revert reference to MR?

### ISSUE THREAD

**Issue by ibaum** [dependencies-io/support#44]
Due to what I believe were errors in my git-repos configuration file, Merge Requests with insufficient changes were created for my project.

I've tried updating the configuration, but the merge requests weren't receiving any updates. 

Going to their corresponding pages in the Manifests section shows a reference to the MR. Even if the MR is closed or merged. 

Is there any way to either remove the reference to the MR, or force it to be updated using a new configuration?

**Comment by davegaeddert** [comment]
Ok, they should both have been removed.

**Comment by ibaum** [comment]
Thanks @davegaeddert 

Is there a better workflow for changes that I should be aware of? I'd rather avoid opening an issue each time I need to make a change.

**Comment by davegaeddert** [comment]
You mean in terms of correcting merge requests?

**Comment by ibaum** [comment]
Correcting merge requests, or integrating the service in general. 

While we test everything, there may be a fair number of merge requests we don't want to actually merge.

Should they be updated with changes to dependencies.yml or git_repos.yml? I didn't see a clear indication in the documentation.

**Comment by davegaeddert** [comment]
Once a merge request is made, it won't be updated. We're planning to add a button to manually request a MR be updated/re-created, but don't have it yet. Let me know if that answers your question... Getting started is probably the hardest part. We're working through a few different things to make that easier but they are bigger picture questions that we're not quite ready to pull the trigger on yet.

**Comment by ibaum** [comment]
Thanks @davegaeddert.  I do think that answers my questions.
