### ISSUE TITLE
Changelog for pycparser

### ISSUE THREAD

**Issue by rrueth** [dependencies-io/support#45]
```
pycparser
This dependency is located in requirements.txt and was updated from "2.18" to "2.19".

We didn't find any content for 2.19. Feel free to open an issue at https://github.com/dependencies-io/support to suggest any improvements.
```

The changelog can be found at:
https://github.com/eliben/pycparser/blob/master/CHANGES

**Comment by davegaeddert** [comment]
Fixed

**Comment by rrueth** [comment]
I just ran this update again today, and saw the same error.

**Comment by davegaeddert** [comment]
Not sure what changed, but I'm pushing an update now that has been tested again to work... Thanks!
