### ISSUE TITLE
Changelog for sqlalchemy

### ISSUE THREAD

**Issue by rrueth** [dependencies-io/support#54]
```
sqlalchemy
This dependency is located in requirements.txt and was updated from "1.2.0" to "1.2.14".

We didn't find any content for 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 1.2.10, 1.2.11, 1.2.12, 1.2.13, or 1.2.14. Feel free to open an issue at https://github.com/dependencies-io/support to suggest any improvements.
```

v1.2 changelogs can be found at: https://github.com/zzzeek/sqlalchemy/blob/master/doc/build/changelog/changelog_12.rst

v1.3 at: https://github.com/zzzeek/sqlalchemy/blob/master/doc/build/changelog/changelog_13.rst

etc.

**Comment by davegaeddert** [comment]
Unfortunately they don't seem to make the location of their GitHub repo very obvious. I don't see it anywhere in the pypi data (https://pypi.org/pypi/SQLAlchemy/json), or even on their website (view-source:https://www.sqlalchemy.org/).

Not sure what else we can do about this one right now... Let me know if you have suggestions.
