### ISSUE TITLE
Cannot remove project

### ISSUE THREAD

**Issue by Vinnl** [dependencies-io/support#66]
When I try to remove a project from dependencies.io through its settings, I receive an error:

> Error saving settings: Network error: Origin https://app.dependencies.io is not allowed by Access-Control-Allow-Origin.

![image](https://user-images.githubusercontent.com/4251/53742162-4aa83700-3e98-11e9-9723-383fc2309867.png)

**Comment by davegaeddert** [comment]
Hey @Vinnl -- you might try it one more time and see if the issue still exists. If you're still having trouble then I can remove the project for you in the meantime, just let me know the name (here or support@dependencies.io).

**Comment by Vinnl** [comment]
Thanks @davegaeddert, I've tried it multiple times over the past weeks, and again just now - the issue persists. The project is https://app.dependencies.io/projects/gitlab/Flockademic/Flockademic

**Comment by davegaeddert** [comment]
Ok, I've deleted your project. Thanks for raising the issue.

**Comment by Vinnl** [comment]
Thanks!
