### ISSUE TITLE
Changelogs not found for various Terraform/Hashicorp repositories

### ISSUE THREAD

**Issue by rrueth** [dependencies-io/support#68]
I'm using the Git repository updates for the following repositories.  Dependencies.io was not able to find the Changelogs for any of the following Git repos:
- https://github.com/terraform-providers/terraform-provider-aws/
- https://github.com/terraform-providers/terraform-provider-null/
- https://github.com/terraform-providers/terraform-provider-template
- https://github.com/hashicorp/packer/

In all cases the change logs are located at the base of the repository in a file named `CHANGELOG.md`.

**Comment by davegaeddert** [comment]
Pushing a fix now -- thanks @rrueth!
