### ISSUE TITLE
Allow changing of gitlab token for an existing project

### ISSUE THREAD

**Issue by Floppy** [dependencies-io/support#69]
Currently (afaict) if I want to change the gitlab token, I need to remove my projects and re-add them. It would be helpful to be able to change the token in settings, or even better, apply it globally.

**Comment by davegaeddert** [comment]
You're correct, and good point. Right now I'm working on the next major version (v3) of dependencies.io which will run in other CI providers instead -- so this issue won't be applicable (or will be different at least). I think I'd rather focus on pushing v3 forward than tackle this right now. If you're interested in using v3 when it's ready or trying a beta version, you can leave your email address here: https://www.dependencies.io/

Thanks!

**Comment by Floppy** [comment]
Great, thanks! cc @Gisleburt you might like to get on that v3 beta, perhaps.
