### ISSUE TITLE
Will it be free for Open Source projects?

### ISSUE THREAD

**Issue by Hypnosphi** [dependencies-io/support#9]
Unfortunately, this is unclear from the website

**Comment by davegaeddert** [comment]
Hey @Hypnosphi, good question. We're in the middle of finishing up pricing and hope to make it public soon. We've decided that there will definitely be a free option for open source projects. It will probably be free to have weekly automated builds (every Monday).

**Comment by davegaeddert** [comment]
All this information is now up on https://www.dependencies.io/pricing/
